name: Change issue label based on column

on:
  project_card:
    types:
      - moved

jobs:
  change-label:
    runs-on: ubuntu-latest

    steps:
      - name: Get column name
        id: get_column_name
        run: |
          echo "::set-output name=column_name::${{ github.event.project_card.column_name }}"

      - name: Change issue label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.REPO_WORKFLOW_TOKEN }}
          script: |
            const columnLabel = context.payload.project_card.column_name;
            const issueNumber = context.payload.project_card.content_url.split('/').pop();
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            const { data: issue } = await octokit.rest.issues.get({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issueNumber });
            const labels = issue.labels.map(label => label.name);

            if (!labels.includes(columnLabel)) {
              await octokit.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: [columnLabel]
              });
            }
