name: Auto Move Issue to "In Progress" Column

on:
  issues:
    types:
      - labeled

jobs:
  auto-move:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue label is "In Progress"
        id: check_label
        run: |
          echo "::set-output name=is_in_progress::${{ contains(github.event.issue.labels.*.name, 'In Progress') }}"

      - name: Move issue to "In Progress" column and remove "Done" label
        if: steps.check_label.outputs.is_in_progress == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SUPER_ADMIN_TOKEN  }}
          script: |
            const { context, github } = require('@actions/github');

            const issueNumber = context.payload.issue.number;

            // Move issue to "In Progress" column
            await github.projects.moveCard({
              card_id: context.payload.issue.project_card.id,
              position: 'top',
              column_id: '47fc9ee4' // Replace with the actual column ID of the "In Progress" column
            });

            // Remove "Done" label if it exists
            await github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              name: 'Done'
            });
